### ISSUE TITLE
Echo'ing code escapes it

### ISSUE THREAD

**Issue by davidyell** [UnionOfRAD/sphere#1]
I think with the default output being escaped, sphere is displaying code snippets escaped making them hard to read. It looks like the wiki/md markup is working as it wraps code properly when placed in ` but still escaped.

Example, http://sphere.orchestra.io/p/Changing-the-layout

Ta,
Dave

**Comment by Ciaro** [comment]
Yeah, Sphere needs some love ^^

**Comment by davidyell** [comment]
There is a nice MarkDown li3 library which seems to work for me.

https://github.com/sandelius/li3_markdown

**Comment by gwoo** [comment]
Here are the libraries in use. https://github.com/UnionOfRAD/sphere/tree/master/libraries

**Comment by davidyell** [comment]
Wow, two years is a long time.
